# Generated by Django 4.2.23 on 2025-08-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('amount', models.FloatField()),
                ('cost', models.FloatField(default=0)),
                ('product', models.CharField(max_length=80)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
    ]
