# Generated by Django 4.2.23 on 2025-08-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_product_region_metricpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.AlterField(
            model_name='metricpoint',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='metricpoint',
            name='orders',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='metricpoint',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.product'),
        ),
        migrations.AlterField(
            model_name='metricpoint',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.region'),
        ),
        migrations.AlterField(
            model_name='metricpoint',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='metricpoint',
            name='users',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='metricpoint',
            index=models.Index(fields=['date'], name='analytics_m_date_a20984_idx'),
        ),
        migrations.AddIndex(
            model_name='metricpoint',
            index=models.Index(fields=['product', 'region'], name='analytics_m_product_b4bcb9_idx'),
        ),
    ]
