# Generated by Django 4.2.23 on 2025-08-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Analytics', max_length=120)),
                ('theme', models.JSONField(default=dict)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kpi', 'KPI'), ('timeseries', 'TimeSeries'), ('bar', 'Bar'), ('pie', 'Pie'), ('table', 'Table')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('config', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
                ('refresh_seconds', models.IntegerField(default=300)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='dashboards.widget')),
            ],
        ),
    ]
